"""Add unique constraint for chapter_number and project_id

Revision ID: 8143bb525516
Revises: 9b1a9dddde19
Create Date: 2025-08-04 13:42:34.409043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8143bb525516'
down_revision: Union[str, Sequence[str], None] = '9b1a9dddde19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite不支持直接添加约束，使用批量模式
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_chapter_project_number',
            ['project_id', 'chapter_number']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除唯一约束
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chapter_project_number', type_='unique')
    # ### end Alembic commands ###
