"""initial_migration

Revision ID: 95ec18802f56
Revises: 
Create Date: 2025-08-21 15:26:36.819762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ec18802f56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chapter_project_number', type_='unique')

    op.add_column('model_configs', sa.Column('proxy_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'proxy_url')
    op.create_unique_constraint('uq_chapter_project_number', 'chapters', ['project_id', 'chapter_number'])
    # ### end Alembic commands ###
