"""Add word_count and chapter_count to projects table

Revision ID: 9b1a9dddde19
Revises: 
Create Date: 2025-07-31 14:38:07.296802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1a9dddde19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('chapter_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'chapter_count')
    op.drop_column('projects', 'word_count')
    # ### end Alembic commands ###
