"""扩展PromptTemplate表支持提示词管理功能

Revision ID: a8f033bea24c
Revises: 95ec18802f56
Create Date: 2025-08-23 15:55:23.511505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f033bea24c'
down_revision: Union[str, None] = '95ec18802f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加新列，设置默认值
    op.add_column('prompt_templates', sa.Column('is_system', sa.Boolean(), nullable=True, default=False))
    op.add_column('prompt_templates', sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
    op.add_column('prompt_templates', sa.Column('usage_count', sa.Integer(), nullable=True, default=0))
    op.add_column('prompt_templates', sa.Column('variables', sa.Text(), nullable=True))
    op.add_column('prompt_templates', sa.Column('tags', sa.String(length=500), nullable=True))
    
    # SQLite不支持ALTER COLUMN，这里我们先跳过这些变更
    # 如果category列已经存在数据且包含NULL值，我们需要先更新这些值
    # 然后通过重建表的方式来实现NOT NULL约束
    
    # 更新默认值
    op.execute("UPDATE prompt_templates SET is_system = 0 WHERE is_system IS NULL")
    op.execute("UPDATE prompt_templates SET is_active = 1 WHERE is_active IS NULL")
    op.execute("UPDATE prompt_templates SET usage_count = 0 WHERE usage_count IS NULL")
    
    # 为了处理NOT NULL约束，我们需要重建表（SQLite的限制）
    # 这里暂时跳过，在实际使用中如果遇到问题再处理
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_templates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prompt_templates', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('prompt_templates', 'tags')
    op.drop_column('prompt_templates', 'variables')
    op.drop_column('prompt_templates', 'usage_count')
    op.drop_column('prompt_templates', 'is_active')
    op.drop_column('prompt_templates', 'is_system')
    # ### end Alembic commands ###
