"""add_llm_parameters_to_model_config

Revision ID: f0b36e979082
Revises: 8143bb525516
Create Date: 2025-08-07 13:30:39.665909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b36e979082'
down_revision: Union[str, Sequence[str], None] = '8143bb525516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_configs', sa.Column('api_url', sa.String(length=500), nullable=True))
    op.add_column('model_configs', sa.Column('top_p', sa.String(length=10), nullable=True, server_default='1.0'))
    op.add_column('model_configs', sa.Column('top_k', sa.Integer(), nullable=True, server_default='40'))
    op.add_column('model_configs', sa.Column('frequency_penalty', sa.String(length=10), nullable=True, server_default='0.0'))
    op.add_column('model_configs', sa.Column('presence_penalty', sa.String(length=10), nullable=True, server_default='0.0'))
    op.add_column('model_configs', sa.Column('stop_sequences', sa.Text(), nullable=True))
    op.add_column('model_configs', sa.Column('stream', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('model_configs', sa.Column('logprobs', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('model_configs', sa.Column('top_logprobs', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'top_logprobs')
    op.drop_column('model_configs', 'logprobs')
    op.drop_column('model_configs', 'stream')
    op.drop_column('model_configs', 'stop_sequences')
    op.drop_column('model_configs', 'presence_penalty')
    op.drop_column('model_configs', 'frequency_penalty')
    op.drop_column('model_configs', 'top_k')
    op.drop_column('model_configs', 'top_p')
    op.drop_column('model_configs', 'api_url')
    # ### end Alembic commands ###
